theme: jekyll-theme-slate
title: Adventures in App Development
description: Tips, tricks and other stories related to application development, expecially as it relates to technologies such as Microsoft Azure, .NET and DevOps.